# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gkueny
name: Gkueny
email: gaetankueny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Etudiant en 2ième année de DUT informatique,
  je suis passioné par la programmation web,
  et particulièrement par Symfony et WordPress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gkueny.fr" # the base hostname & protocol for your site
twitter_username: gaetankueny
github_username:  gkueny
linkedin_username: gaëtan-kueny-017b87b7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 3

environment: prod

gems: [jekyll-paginate, jekyll-compose, jekyll-gist, jekyll-sitemap]
